### ISSUE TITLE
[EA/FA] BilinearFormExtension omitted boundary conditions 

### ISSUE THREAD

**Issue by camierjs** [mfem/mfem#2699]
I've encountered this issue when using `FormSystemMatrix` on a `Par`/`BilinearForm` using `FormSystemMatrix`.

The `EA`/`FA` extensions fold back to the `PA` `FormSystemMatrix` method which does not set properly the boundary conditions on the assembled matrix.

In serial, `EliminateVDofs(ess_dofs, Operator::DIAG_KEEP)` followed by a `Finalize()` will add them.

In parallel, https://github.com/mfem/mfem/blob/7e8d8b1d55adecfb46f971300f820bd7e48bdc67/fem/pbilinearform.cpp#L422-L442
would work but it requires to change the `extension` code path and does not use `GPU` capabilities.

**Comment by rcarson3** [comment]
I'm guessing due to how `BilinearForm` and `LinearForm` it wouldn't be possible to emulate how the `NonlinearForm` handles BCs?

https://github.com/mfem/mfem/blob/7e8d8b1d55adecfb46f971300f820bd7e48bdc67/fem/nonlinearform.cpp#L152-L165

https://github.com/mfem/mfem/blob/7e8d8b1d55adecfb46f971300f820bd7e48bdc67/fem/pnonlinearform.cpp#L89-L94

It's been quite sometime since I looked at how the bilinearform implemented things and trying to figure out why it does what it does, but I know the nonlinearforms should work on the GPU.

**Comment by tzanio** [comment]
@YohannDudouit and @camierjs, is this still an issue?

**Comment by YohannDudouit** [comment]
I believe this has been fixed with https://github.com/mfem/mfem/pull/3056 .

**Comment by tzanio** [comment]
@camierjs, can you confirm ☝️

**Comment by camierjs** [comment]
I am still having issues with `FormSystemMatrix`, the `DiagonalPolicy` and now `EliminateVDofs`.

`DiagonalPolicy::DIAG_ONE` seems to be only supported by `FABilinearFormExtension::EliminateBC`: only the comment allows to know this and is not checked against the `SetDiagonalPolicy` of the bilinear form.

`EliminateVDofs` does not allow to get the same matrices anymore, even with `DiagonalPolicy::DIAG_ONE`.

**Comment by YohannDudouit** [comment]
We can talk more about it during the PR meeting, but this would require a refactor to take into account the diagonal policy. Here is a temporary fix: https://github.com/mfem/mfem/pull/3127
